sudo: required
services:
  - docker

before_install:
  - docker build -t blueseal/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run blueseal/udemy-docker-react npm run test -- --coverage
