sudo: required
services:
  - docker

before_install:
  - docker build -t blueseal/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true blueseal/udemy-docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "udemy-docker-react"
  env: "UdemyDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-840584655565"
  bucket_path: "udemy-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
